# This is a gateway config.
name: gateway
version: v1
middlewares:
#  - name: tracing
#    options:
#      '@type': type.googleapis.com/gateway.middleware.tracing.v1.Tracing
#      httpEndpoint: 'localhost:4318' # default opentelemetry collector port
  - name: logging
  - name: transcoder
  - name: cors
    options:
      allowHeaders:
        - Authorization
      '@type': type.googleapis.com/gateway.middleware.cors.v1.Cors
      allowCredentials: true
      allowOrigins:
        - '*'
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
endpoints:
  - path: /api/admin/*
    timeout: 3s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8001'
#      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: {"success":0.6, "request":"1", "bucket":"10", "window":"3s"}
          backupService: {"endpoint":{"backends":[{"target":"127.0.0.1:8001"}]}}
          assertCondtions:
          - {"by_status_code":"200"}
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
#          stripPrefix: /bbs
  - path: /api/system/*
    timeout: 3s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8001'
    #      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: {"success":0.6, "request":"1", "bucket":"10", "window":"3s"}
          backupService: {"endpoint":{"backends":[{"target":"127.0.0.1:8001"}]}}
          assertCondtions:
            - {"by_status_code":"200"}
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
  #          stripPrefix: /bbs
  - path: /api/bird/*
    timeout: 3s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8002'
    #      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: {"success":0.6, "request":"1", "bucket":"10", "window":"3s"}
          backupService: {"endpoint":{"backends":[{"target":"127.0.0.1:8001"}]}}
          assertCondtions:
            - {"by_status_code":"200"}
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
  #          stripPrefix: /bbs
  - path: /api/device/*
    timeout: 3s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8003'
    #      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: {"success":0.6, "request":"1", "bucket":"10", "window":"3s"}
          backupService: {"endpoint":{"backends":[{"target":"127.0.0.1:8001"}]}}
          assertCondtions:
            - {"by_status_code":"200"}
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
  #          stripPrefix: /bbs
  - path: /api/media/*
    timeout: 3s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8004'
    #      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: {"success":0.6, "request":"1", "bucket":"10", "window":"3s"}
          backupService: {"endpoint":{"backends":[{"target":"127.0.0.1:8001"}]}}
          assertCondtions:
            - {"by_status_code":"200"}
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
  #          stripPrefix: /bbs
  - path: /api/ai/*
    timeout: 25s
    protocol: HTTP
    host: localhost
    backends:
      - target: '127.0.0.1:8005'
    #      - target: 'discovery:///bbs'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: { "success": 0.6, "request": "1", "bucket": "10", "window": "3s" }
          backupService: { "endpoint": { "backends": [ { "target": "127.0.0.1:8001" } ] } }
          assertCondtions:
            - { "by_status_code": "200" }
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
  #          stripPrefix: /bbs